name: build-and-publish
on: workflow_dispatch
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Install Node.js with pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Configure Git to use HTTPS
        run: git config --global url."https://github.com/".insteadOf git@github.com:
      - name: Remove lockfile and install dependencies
        run: |
          rm -f pnpm-lock.yaml
          pnpm install --no-frozen-lockfile
        env:
          GIT_TERMINAL_PROMPT: 0    
      - run: pnpm install
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.65
      - run: pnpm build
      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}